spring:
  application:
    name: shop-management-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: ${SERVER_PORT:8081}
